Repository neo-empresarial/clockify-integration, pull requests merged in 2019-11, with the labels that each got.

#28 Add 'is_clt' to Member model
  models/member.py
Labels: enhancement

#32 Change strings from models to be lower case
  models/activity.py
  models/client.py
  models/member.py
  models/project.py
  models/time_entry.py
Labels: enhancement

#41 Insert bulk db transaction
  .codeclimate.yml
  .gitignore
  Pipfile
  Pipfile.lock
  config/settings.py
  models/time_entry.py
  old_timesheet_migration/timesheet_migration.py
  orator_config.py
  orator_development.py
  orator_devolopment.py
  services/populate.py
  setup.cfg
Labels: enhancement

#44 Autofix clockify
  Pipfile
  Pipfile.lock
  config/__init__.py
  models/config.py
  models/time_entry.py
Labels: good first issue

#51 Remove unused main.py
  main.py
Labels: bug

#49 Move config to models.__init__ (Issue #48)
  Pipfile
  Pipfile.lock
  config/__init__.py
  config/settings.py
  handler.py
  models/__init__.py
  models/activity.py
  models/client.py
  models/config.py
  models/member.py
  models/project.py
  models/time_entry.py
  old_timesheet_migration/timesheet_migration.py
  services/populate.py
  update_member_clt.py
Labels: bug, enhancement

#42 Update README to reflect orator migration
  README.md
Labels: documentation

#59 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature
